import { ImageSourcePropType } from "react-native";

export type CultureTechnicalDetails = {
  sowingPeriod: string;
  method: string;
  depth: string;
  rowSpacing: string;
  plantSpacing: string;
  seedRate: string;
  harvest: string;
  waterNeeds: string;
  fertilization: string;
  diseases: string[];
};

export type Culture = {
  title: string;
  image: ImageSourcePropType;
  recommended?: boolean;
  technicalDetails: CultureTechnicalDetails;
};

export type CultureGroup = {
  title: string;
  cultures: Culture[];
};

export const CULTURE_GROUPS: CultureGroup[] = [
  {
    title: "Céréales",
    cultures: [
      {
        title: "Blé",
        image: require("../assets/images/wheat.jpg"),
        recommended: true,
        technicalDetails: {
          sowingPeriod: "Octobre–décembre",
          method: "Semis en lignes avec semoir",
          depth: "3–5 cm",
          rowSpacing: "15–20 cm",
          plantSpacing: "3–5 cm",
          seedRate: "180–220 kg/ha",
          harvest: "Mai–juin, environ 180–220 jours après semis",
          waterNeeds: "450–600 mm/cycle",
          fertilization:
            "N 120–180 kg/ha ; P₂O₅ 50–80 kg/ha ; K₂O 60–100 kg/ha",
          diseases: ["Rouille brune", "Oïdium", "Septoriose"],
        },
      },
      {
        title: "Orge",
        image: require("../assets/images/cultures/barley.jpg"),
        recommended: true,
        technicalDetails: {
          sowingPeriod: "Octobre–novembre",
          method: "Semis en lignes avec semoir",
          depth: "3–5 cm",
          rowSpacing: "15–20 cm",
          plantSpacing: "3–5 cm",
          seedRate: "140–190 kg/ha",
          harvest: "Mai–juin, environ 160–200 jours après semis",
          waterNeeds: "350–500 mm/cycle",
          fertilization: "N 90–150 kg/ha ; P₂O₅ 40–70 kg/ha ; K₂O 50–90 kg/ha",
          diseases: ["Helminthosporiose", "Rouille naine", "Oïdium"],
        },
      },
      {
        title: "Avoine",
        image: require("../assets/images/cultures/oats.jpg"),
        technicalDetails: {
          sowingPeriod: "Octobre–décembre",
          method: "Semis en lignes",
          depth: "3–5 cm",
          rowSpacing: "15–20 cm",
          plantSpacing: "4–6 cm",
          seedRate: "100–160 kg/ha",
          harvest: "Mai–juin, 160–210 jours après semis",
          waterNeeds: "400–550 mm/cycle",
          fertilization: "N 80–130 kg/ha ; P₂O₅ 40–60 kg/ha ; K₂O 50–80 kg/ha",
          diseases: ["Rouille couronnée", "Oïdium", "Septoriose"],
        },
      },
      {
        title: "Maïs",
        image: require("../assets/images/cultures/corns.jpg"),
        recommended: true,
        technicalDetails: {
          sowingPeriod: "Avril–mai",
          method: "Semis en lignes avec semoir",
          depth: "3–5 cm",
          rowSpacing: "70–75 cm",
          plantSpacing: "15–20 cm",
          seedRate: "20–30 kg/ha",
          harvest: "Juillet–septembre, 90–120 jours après semis",
          waterNeeds: "500–700 mm/cycle",
          fertilization:
            "N 150–200 kg/ha ; P₂O₅ 60–90 kg/ha ; K₂O 80–120 kg/ha",
          diseases: ["Helminthosporiose", "Rouille du maïs", "Fusariose"],
        },
      },
      {
        title: "Sorgho",
        image: require("../assets/images/cultures/Sorghum.jpg"),
        technicalDetails: {
          sowingPeriod: "Avril–mai",
          method: "Semis en lignes",
          depth: "2–4 cm",
          rowSpacing: "45–60 cm",
          plantSpacing: "10–15 cm",
          seedRate: "8–15 kg/ha",
          harvest: "Août–septembre, 100–130 jours après semis",
          waterNeeds: "350–500 mm/cycle",
          fertilization:
            "N 100–160 kg/ha ; P₂O₅ 50–70 kg/ha ; K₂O 60–100 kg/ha",
          diseases: ["Anthracnose", "Rouille", "Fusariose"],
        },
      },
      {
        title: "Seigle",
        image: require("../assets/images/cultures/rye.jpg"),
        technicalDetails: {
          sowingPeriod: "Octobre–novembre",
          method: "Semis en lignes",
          depth: "3–5 cm",
          rowSpacing: "15–20 cm",
          plantSpacing: "3–5 cm",
          seedRate: "120–180 kg/ha",
          harvest: "Juin–juillet, 190–230 jours après semis",
          waterNeeds: "350–500 mm/cycle",
          fertilization: "N 90–140 kg/ha ; P₂O₅ 40–70 kg/ha ; K₂O 50–90 kg/ha",
          diseases: ["Rouille brune", "Ergot", "Oïdium"],
        },
      },
    ],
  },
  {
    title: "Arbres fruitiers",
    cultures: [
      {
        title: "Olivier",
        image: require("../assets/images/olives.jpg"),
        recommended: true,
        technicalDetails: {
          sowingPeriod: "Octobre–mars pour les jeunes plants",
          method: "Plantation de plants greffés",
          depth: "Collet au niveau du sol",
          rowSpacing: "6–8 m",
          plantSpacing: "5–7 m",
          seedRate: "150–250 plants/ha",
          harvest: "Octobre–janvier, selon la variété",
          waterNeeds: "400–600 mm/cycle",
          fertilization:
            "N 80–150 kg/ha ; P₂O₅ 40–70 kg/ha ; K₂O 100–180 kg/ha",
          diseases: ["Mouche de l’olive", "Œil de paon", "Verticilliose"],
        },
      },
      {
        title: "Oranger",
        image: require("../assets/images/oranges.jpg"),
        recommended: true,
        technicalDetails: {
          sowingPeriod: "Octobre–mars pour les jeunes plants",
          method: "Plantation de plants greffés",
          depth: "Collet au niveau du sol",
          rowSpacing: "5–6 m",
          plantSpacing: "4–5 m",
          seedRate: "350–500 plants/ha",
          harvest: "Novembre–mars, selon la variété",
          waterNeeds: "700–1 000 mm/cycle",
          fertilization:
            "N 150–250 kg/ha ; P₂O₅ 60–100 kg/ha ; K₂O 150–250 kg/ha",
          diseases: ["Cératite", "Gommose", "Mal secco"],
        },
      },
      {
        title: "Citronnier",
        image: require("../assets/images/cultures/lemons.jpg"),
        recommended: true,
        technicalDetails: {
          sowingPeriod: "Octobre–mars pour les jeunes plants",
          method: "Plantation de plants greffés",
          depth: "Collet au niveau du sol",
          rowSpacing: "5–6 m",
          plantSpacing: "4–5 m",
          seedRate: "350–500 plants/ha",
          harvest: "Toute l’année, avec pics en hiver et au printemps",
          waterNeeds: "800–1 100 mm/cycle",
          fertilization:
            "N 160–260 kg/ha ; P₂O₅ 60–100 kg/ha ; K₂O 160–260 kg/ha",
          diseases: ["Mineuse des agrumes", "Gommose", "Tristeza"],
        },
      },
      {
        title: "Amandier",
        image: require("../assets/images/cultures/almonds_tree.jpg"),
        recommended: true,
        technicalDetails: {
          sowingPeriod: "Novembre–mars pour les jeunes plants",
          method: "Plantation de plants greffés",
          depth: "Collet au niveau du sol",
          rowSpacing: "6–7 m",
          plantSpacing: "5–6 m",
          seedRate: "250–350 plants/ha",
          harvest: "Août–septembre",
          waterNeeds: "500–700 mm/cycle",
          fertilization: "N 80–140 kg/ha ; P₂O₅ 40–70 kg/ha ; K₂O 80–140 kg/ha",
          diseases: ["Moniliose", "Fusicoccum", "Puceron vert"],
        },
      },
      {
        title: "Figuier",
        image: require("../assets/images/cultures/figs.jpg"),
        technicalDetails: {
          sowingPeriod: "Novembre–mars pour les jeunes plants",
          method: "Plantation de plants ou boutures enracinées",
          depth: "Collet au niveau du sol",
          rowSpacing: "6–8 m",
          plantSpacing: "5–7 m",
          seedRate: "200–300 plants/ha",
          harvest: "Juin–septembre, en plusieurs passages",
          waterNeeds: "500–700 mm/cycle",
          fertilization: "N 60–120 kg/ha ; P₂O₅ 30–60 kg/ha ; K₂O 80–140 kg/ha",
          diseases: ["Mosaïque du figuier", "Rouille", "Cochenille"],
        },
      },
      {
        title: "Grenadier",
        image: require("../assets/images/cultures/pomegranates.jpg"),
        technicalDetails: {
          sowingPeriod: "Novembre–mars pour les jeunes plants",
          method: "Plantation de plants greffés ou boutures",
          depth: "Collet au niveau du sol",
          rowSpacing: "5–6 m",
          plantSpacing: "4–5 m",
          seedRate: "350–500 plants/ha",
          harvest: "Septembre–novembre",
          waterNeeds: "500–700 mm/cycle",
          fertilization: "N 80–150 kg/ha ; P₂O₅ 40–70 kg/ha ; K₂O 80–150 kg/ha",
          diseases: ["Alternariose", "Pourriture des fruits", "Puceron"],
        },
      },
    ],
  },
  {
    title: "Légumineuses",
    cultures: [
      {
        title: "Pois chiche",
        image: require("../assets/images/cultures/chickpea.jpg"),
        recommended: true,
        technicalDetails: {
          sowingPeriod: "Février–mars ou octobre–novembre",
          method: "Semis en lignes",
          depth: "4–6 cm",
          rowSpacing: "30–40 cm",
          plantSpacing: "10–15 cm",
          seedRate: "80–120 kg/ha",
          harvest: "Juin–juillet, 100–130 jours après semis",
          waterNeeds: "250–400 mm/cycle",
          fertilization: "N 20–40 kg/ha ; P₂O₅ 50–80 kg/ha ; K₂O 40–70 kg/ha",
          diseases: ["Ascochytose", "Fusariose", "Chenille de la gousse"],
        },
      },
      {
        title: "Lentille",
        image: require("../assets/images/cultures/Brown_lentils.jpg"),
        recommended: true,
        technicalDetails: {
          sowingPeriod: "Novembre–décembre",
          method: "Semis en lignes",
          depth: "2–4 cm",
          rowSpacing: "15–25 cm",
          plantSpacing: "3–5 cm",
          seedRate: "60–100 kg/ha",
          harvest: "Mai–juin, 100–130 jours après semis",
          waterNeeds: "250–350 mm/cycle",
          fertilization: "N 20–35 kg/ha ; P₂O₅ 40–70 kg/ha ; K₂O 30–60 kg/ha",
          diseases: ["Ascochytose", "Botrytis", "Rouille"],
        },
      },
      {
        title: "Fève",
        image: require("../assets/images/cultures/Broad_bean.jpg"),
        technicalDetails: {
          sowingPeriod: "Octobre–décembre",
          method: "Semis en poquets ou en lignes",
          depth: "5–8 cm",
          rowSpacing: "40–60 cm",
          plantSpacing: "15–25 cm",
          seedRate: "120–180 kg/ha",
          harvest: "Avril–juin, en vert ou à maturité sèche",
          waterNeeds: "350–500 mm/cycle",
          fertilization: "N 20–40 kg/ha ; P₂O₅ 50–80 kg/ha ; K₂O 50–90 kg/ha",
          diseases: ["Rouille", "Botrytis", "Puceron noir"],
        },
      },
      {
        title: "Pois",
        image: require("../assets/images/cultures/peas.jpg"),
        technicalDetails: {
          sowingPeriod: "Octobre–février",
          method: "Semis en lignes",
          depth: "3–5 cm",
          rowSpacing: "30–45 cm",
          plantSpacing: "5–10 cm",
          seedRate: "120–200 kg/ha",
          harvest: "Avril–juin, 70–110 jours après semis",
          waterNeeds: "300–450 mm/cycle",
          fertilization: "N 20–35 kg/ha ; P₂O₅ 40–70 kg/ha ; K₂O 40–80 kg/ha",
          diseases: ["Mildiou", "Oïdium", "Puceron vert"],
        },
      },
      {
        title: "Haricot",
        image: require("../assets/images/cultures/white_beans.jpg"),
        technicalDetails: {
          sowingPeriod: "Avril–juin",
          method: "Semis en poquets ou en lignes",
          depth: "3–5 cm",
          rowSpacing: "40–60 cm",
          plantSpacing: "10–15 cm",
          seedRate: "80–140 kg/ha",
          harvest: "Juin–septembre, 70–110 jours après semis",
          waterNeeds: "350–500 mm/cycle",
          fertilization: "N 40–80 kg/ha ; P₂O₅ 50–80 kg/ha ; K₂O 80–130 kg/ha",
          diseases: ["Anthracnose", "Rouille", "Mosaïque du haricot"],
        },
      },
      {
        title: "Soja",
        image: require("../assets/images/cultures/Soybeans.jpg"),
        technicalDetails: {
          sowingPeriod: "Avril–mai",
          method: "Semis en lignes avec semoir",
          depth: "3–5 cm",
          rowSpacing: "40–50 cm",
          plantSpacing: "4–7 cm",
          seedRate: "60–100 kg/ha",
          harvest: "Septembre–octobre, 110–150 jours après semis",
          waterNeeds: "450–650 mm/cycle",
          fertilization: "N 20–40 kg/ha ; P₂O₅ 50–80 kg/ha ; K₂O 70–120 kg/ha",
          diseases: ["Sclérotiniose", "Mildiou", "Puceron du soja"],
        },
      },
    ],
  },
  {
    title: "Cultures maraîchères",
    cultures: [
      {
        title: "Tomate",
        image: require("../assets/images/cultures/tomatos.jpg"),
        recommended: true,
        technicalDetails: {
          sowingPeriod: "Février–avril sous abri, avril–mai en plein champ",
          method: "Plantation de plants en lignes",
          depth: "Plantation jusqu’aux premières feuilles",
          rowSpacing: "80–100 cm",
          plantSpacing: "40–60 cm",
          seedRate: "15 000–25 000 plants/ha",
          harvest: "Juin–octobre, 70–100 jours après plantation",
          waterNeeds: "500–700 mm/cycle",
          fertilization:
            "N 150–220 kg/ha ; P₂O₅ 80–120 kg/ha ; K₂O 200–300 kg/ha",
          diseases: ["Mildiou", "Alternariose", "Nécrose apicale"],
        },
      },
      {
        title: "Pomme de terre",
        image: require("../assets/images/cultures/potatos.jpg"),
        technicalDetails: {
          sowingPeriod: "Février–avril",
          method: "Plantation de tubercules en billons",
          depth: "5–10 cm",
          rowSpacing: "60–75 cm",
          plantSpacing: "25–35 cm",
          seedRate: "1 500–2 500 kg/ha",
          harvest: "Mai–août, 90–120 jours après plantation",
          waterNeeds: "450–650 mm/cycle",
          fertilization:
            "N 120–180 kg/ha ; P₂O₅ 80–120 kg/ha ; K₂O 180–280 kg/ha",
          diseases: ["Mildiou", "Alternariose", "Gale commune"],
        },
      },
      {
        title: "Oignon",
        image: require("../assets/images/cultures/onions.jpg"),
        recommended: true,
        technicalDetails: {
          sowingPeriod: "Septembre–novembre ou janvier–mars",
          method: "Semis direct ou plantation de bulbilles",
          depth: "1–2 cm",
          rowSpacing: "20–30 cm",
          plantSpacing: "8–12 cm",
          seedRate: "3–6 kg/ha",
          harvest: "Mai–août, 120–180 jours après semis",
          waterNeeds: "350–550 mm/cycle",
          fertilization:
            "N 80–140 kg/ha ; P₂O₅ 50–80 kg/ha ; K₂O 100–180 kg/ha",
          diseases: ["Mildiou de l’oignon", "Botrytis", "Thrips"],
        },
      },
      {
        title: "Carotte",
        image: require("../assets/images/cultures/carrots.png"),
        technicalDetails: {
          sowingPeriod: "Octobre–mars, selon la variété",
          method: "Semis direct en lignes",
          depth: "1–2 cm",
          rowSpacing: "25–35 cm",
          plantSpacing: "3–6 cm",
          seedRate: "2–4 kg/ha",
          harvest: "Janvier–juin, 80–120 jours après semis",
          waterNeeds: "350–500 mm/cycle",
          fertilization:
            "N 60–100 kg/ha ; P₂O₅ 40–70 kg/ha ; K₂O 100–160 kg/ha",
          diseases: ["Alternariose", "Oïdium", "Mouche de la carotte"],
        },
      },
      {
        title: "Poivron",
        image: require("../assets/images/cultures/pepper.jpg"),
        technicalDetails: {
          sowingPeriod: "Janvier–mars sous abri",
          method: "Plantation de plants en lignes",
          depth: "Plantation jusqu’à la motte",
          rowSpacing: "70–90 cm",
          plantSpacing: "30–45 cm",
          seedRate: "20 000–35 000 plants/ha",
          harvest: "Juin–octobre, 70–100 jours après plantation",
          waterNeeds: "500–700 mm/cycle",
          fertilization:
            "N 120–200 kg/ha ; P₂O₅ 60–100 kg/ha ; K₂O 180–280 kg/ha",
          diseases: ["Oïdium", "Botrytis", "Puceron"],
        },
      },
      {
        title: "Courgette",
        image: require("../assets/images/cultures/zucchini.jpg"),
        technicalDetails: {
          sowingPeriod: "Mars–juin",
          method: "Semis en poquets ou plantation de plants",
          depth: "2–4 cm",
          rowSpacing: "100–150 cm",
          plantSpacing: "60–100 cm",
          seedRate: "3–6 kg/ha",
          harvest: "Mai–septembre, 45–60 jours après semis",
          waterNeeds: "400–600 mm/cycle",
          fertilization:
            "N 100–160 kg/ha ; P₂O₅ 60–90 kg/ha ; K₂O 150–220 kg/ha",
          diseases: ["Oïdium", "Mildiou", "Virus de la mosaïque"],
        },
      },
    ],
  },
  {
    title: "Plantes aromatiques",
    cultures: [
      {
        title: "Menthe",
        image: require("../assets/images/cultures/mints.jpg"),
        recommended: true,
        technicalDetails: {
          sowingPeriod: "Mars–mai",
          method: "Plantation de boutures ou plants",
          depth: "3–5 cm",
          rowSpacing: "40–60 cm",
          plantSpacing: "20–30 cm",
          seedRate: "30 000–50 000 plants/ha",
          harvest: "Mai–octobre, coupes successives",
          waterNeeds: "500–700 mm/cycle",
          fertilization: "N 80–140 kg/ha ; P₂O₅ 40–70 kg/ha ; K₂O 80–130 kg/ha",
          diseases: ["Rouille de la menthe", "Oïdium", "Puceron"],
        },
      },
      {
        title: "Basilic",
        image: require("../assets/images/cultures/basilic.jpg"),
        technicalDetails: {
          sowingPeriod: "Avril–juin",
          method: "Semis en pépinière puis repiquage",
          depth: "0,5–1 cm",
          rowSpacing: "30–45 cm",
          plantSpacing: "20–30 cm",
          seedRate: "2–4 kg/ha",
          harvest: "Juin–septembre, avant floraison complète",
          waterNeeds: "400–600 mm/cycle",
          fertilization: "N 60–100 kg/ha ; P₂O₅ 30–50 kg/ha ; K₂O 60–100 kg/ha",
          diseases: ["Mildiou du basilic", "Fusariose", "Puceron"],
        },
      },
      {
        title: "Thym",
        image: require("../assets/images/cultures/thyme.jpg"),
        recommended: true,
        technicalDetails: {
          sowingPeriod: "Mars–mai",
          method: "Semis en pépinière ou plantation de boutures",
          depth: "0,5–1 cm",
          rowSpacing: "40–60 cm",
          plantSpacing: "25–35 cm",
          seedRate: "3–5 kg/ha",
          harvest: "Mai–septembre, avant la pleine floraison",
          waterNeeds: "250–400 mm/cycle",
          fertilization: "N 40–70 kg/ha ; P₂O₅ 20–40 kg/ha ; K₂O 40–80 kg/ha",
          diseases: ["Pourriture racinaire", "Oïdium", "Thrips"],
        },
      },
      {
        title: "Romarin",
        image: require("../assets/images/cultures/rosemary.jpg"),
        recommended: true,
        technicalDetails: {
          sowingPeriod: "Mars–mai",
          method: "Plantation de boutures enracinées",
          depth: "3–5 cm",
          rowSpacing: "60–80 cm",
          plantSpacing: "40–60 cm",
          seedRate: "15 000–25 000 plants/ha",
          harvest: "Toute l’année, coupes régulières",
          waterNeeds: "250–400 mm/cycle",
          fertilization: "N 40–80 kg/ha ; P₂O₅ 20–40 kg/ha ; K₂O 40–80 kg/ha",
          diseases: ["Oïdium", "Pourriture du collet", "Cochenille"],
        },
      },
      {
        title: "Coriandre",
        image: require("../assets/images/cultures/coriander.jpg"),
        technicalDetails: {
          sowingPeriod: "Février–octobre",
          method: "Semis direct en lignes",
          depth: "1–2 cm",
          rowSpacing: "20–30 cm",
          plantSpacing: "5–10 cm",
          seedRate: "8–15 kg/ha",
          harvest: "Avril–novembre, 30–60 jours après semis",
          waterNeeds: "250–400 mm/cycle",
          fertilization: "N 50–90 kg/ha ; P₂O₅ 30–50 kg/ha ; K₂O 50–90 kg/ha",
          diseases: ["Oïdium", "Bactériose", "Puceron"],
        },
      },
      {
        title: "Persil",
        image: require("../assets/images/cultures/parsley.jpg"),
        technicalDetails: {
          sowingPeriod: "Février–septembre",
          method: "Semis direct en lignes",
          depth: "1–2 cm",
          rowSpacing: "20–30 cm",
          plantSpacing: "5–10 cm",
          seedRate: "4–8 kg/ha",
          harvest: "Avril–décembre, coupes successives",
          waterNeeds: "300–450 mm/cycle",
          fertilization: "N 60–100 kg/ha ; P₂O₅ 30–50 kg/ha ; K₂O 60–100 kg/ha",
          diseases: ["Septoriose", "Oïdium", "Puceron"],
        },
      },
    ],
  },
];
